using Xunit;
using EveDeck.Models;
using EveDeck.Services;
using EveDeck.ViewModels;

namespace EveDeck.Tests;

// The master/centre rect is derived from geometry rather than stored, so a tie between equally sized
// slots used to be resolved by whichever one enumerated first. In a uniform grid the integer-division
// remainder handed the LAST column and LAST row an extra pixel, which silently made the top-right cell
// the master. These tests pin the tie-break so that can't come back.
public class PickCenterSlotTests
{
    private static LayoutSlot Slot(int n, int x, int y, int w, int h) =>
        new() { SlotNumber = n, X = x, Y = y, Width = w, Height = h };

    [Fact]
    public void ReturnsNullForEmptyInput()
    {
        Assert.Null(MainWindowViewModel.PickCenterSlot(Array.Empty<LayoutSlot>()));
    }

    [Fact]
    public void PicksTheGenuinelyLargestSlot()
    {
        var slots = new[]
        {
            Slot(1, 0, 0, 400, 300),
            Slot(2, 400, 0, 400, 300),
            Slot(3, 0, 300, 1600, 900),   // clearly dominant
            Slot(4, 800, 0, 400, 300),
        };

        Assert.Equal(3, MainWindowViewModel.PickCenterSlot(slots));
    }

    // The actual regression: a 3x3 grid generated by PresetFactory at 2560x1440, where the last column
    // is 854px wide against 853 elsewhere. Three slots tie for largest; the centre cell must win.
    [Fact]
    public void UniformGridPicksTheCentreCellNotTheRemainderCell()
    {
        var profile = new LayoutProfile
        {
            Category = "Grid",
            IsFamilyTemplate = true,
            TemplateWidth = 2560,
            TemplateHeight = 1440,
            TemplateCount = 9,
        };
        PresetFactory.RegenerateFamilySlots(profile);

        Assert.Equal(9, profile.Slots.Count);

        // Sanity-check the premise: more than one slot really does tie for the largest area.
        var maxArea = profile.Slots.Max(s => (long)s.Width * s.Height);
        Assert.True(profile.Slots.Count(s => (long)s.Width * s.Height == maxArea) > 1,
            "expected the integer-division remainder to produce tied largest slots");

        // Slot 5 is the middle cell of a 3x3 laid out row by row.
        Assert.Equal(5, MainWindowViewModel.PickCenterSlot(profile.Slots));
    }

    [Fact]
    public void EvenGridResolvesDeterministicallyToTheLowestSlotNumber()
    {
        // A 2x2 has no true centre cell: all four are equidistant from the centroid, so the tie-break
        // falls through to slot number. The guarantee here is determinism, not a particular corner.
        var slots = new[]
        {
            Slot(1, 0, 0, 640, 360),
            Slot(2, 640, 0, 640, 360),
            Slot(3, 0, 360, 640, 360),
            Slot(4, 640, 360, 640, 360),
        };

        Assert.Equal(1, MainWindowViewModel.PickCenterSlot(slots));
        Assert.Equal(1, MainWindowViewModel.PickCenterSlot(slots.Reverse().ToArray()));
    }

    // Center Master and friends must be completely unaffected by the tie-break: their master rect is
    // far larger than any surrounding tile, so it wins on area before proximity is ever consulted.
    [Theory]
    [InlineData("Center Master", 9)]
    [InlineData("Whammy Board", 9)]
    [InlineData("Side Stack", 5)]
    [InlineData("Twin Stack", 5)]
    public void DominantMasterFamiliesStillPickTheirMasterRect(string category, int count)
    {
        var profile = new LayoutProfile
        {
            Category = category,
            IsFamilyTemplate = true,
            TemplateWidth = 2560,
            TemplateHeight = 1440,
            TemplateCount = count,
        };
        PresetFactory.RegenerateFamilySlots(profile);

        var largest = profile.Slots.OrderByDescending(s => (long)s.Width * s.Height).First();
        Assert.Equal(largest.SlotNumber, MainWindowViewModel.PickCenterSlot(profile.Slots));
    }

    [Fact]
    public void ZeroAreaSlotsFallBackToTheFirstSlot()
    {
        var slots = new[] { Slot(7, 0, 0, 0, 0), Slot(8, 0, 0, 0, 0) };
        Assert.Equal(7, MainWindowViewModel.PickCenterSlot(slots));
    }
}
